name: Frontend CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build-scan-deploy:
    runs-on: [self-hosted, linux]

    steps:
      - name: 📥 Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # NEW: We run npm commands inside a temporary Node container.
      # The '-v' flag mounts your repository code into the container.
      - name: 🧪 Run Tests in Docker
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/app \
            -w /app \
            node:18-alpine \
            sh -c "npm install && npm test -- --watchAll=false"


      - name: 🐳 Build Production Image
        run: docker build -t frontend-ecommerce:latest .

      - name: 🛡️ Trivy Image Scan
        continue-on-error: true
        uses: aquasecurity/trivy-action@master
        env:
          # Forces Trivy to bypass the Google mirror and pull directly from GitHub
          TRIVY_DB_REPOSITORY: public.ecr.aws/aquasecurity/trivy-db:2
        with:
          image-ref: 'frontend-ecommerce:latest' # (Make sure to use 'backend:latest' in the backend file!)
          format: 'table'
          exit-code: '1'
          severity: 'CRITICAL,HIGH'
          # Uses the built-in GitHub token to bypass anonymous rate limiting
          github-pat: ${{ secrets.GITHUB_TOKEN }}
          # Kills the process if it hangs for more than 10 minutes
          timeout: '10m'

      - name: 🚢 Load Image into Kind
        run: kind load docker-image frontend-ecommerce:latest --name kind

      - name: ☸️ Deploy to Kubernetes
        run: |
          kubectl apply -f k8s/
          kubectl rollout restart deployment frontend-deployment || true
